module.exports = {
  getProfile: async (req, res, next) => {},
  getOrders: async (req, res, next) => {},
  getWishlist: async (req, res, next) => {},
  getChat: async (req, res, next) => {},
  getDiscussion: async (req, res, next) => {},
  getReview: async (req, res, next) => {},
  updateProfile: async (req, res, next) => {},
  updatePassword: async (req, res, next) => {},
  updateEmail: async (req, res, next) => {},
  updateCart: async (req, res, next) => {},
  removeOrder: async (req, res, next) => {},
  removeWishlist: async (req, res, next) => {},
  removeCart: async (req, res, next) => {},
};
